# Generated by Django 4.1.5 on 2023-03-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmailing',
            name='monthdates_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дни месяца с пробелами'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='from_email',
            field=models.EmailField(blank=True, default='fuckup@oscarbot.ru', max_length=254, null=True, verbose_name='Email рассылки'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='monthdates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дни месяца cron-формат'),
        ),
    ]
