# Generated by Django 4.1.5 on 2023-03-08 18:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_configmailing_monthdates_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='До 50 символов', max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='До 200 символов', max_length=200, verbose_name='Содержание')),
                ('picture', models.ImageField(upload_to='home/', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('опубликовано', 'ДА'), ('не опубликовано', 'НЕТ')], default='опубликовано', max_length=20, verbose_name='Публиковать?')),
            ],
            options={
                'verbose_name': 'Преимущество на главной',
                'verbose_name_plural': 'Преимущества на главной',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_h1', models.CharField(blank=True, help_text='До 100 символов', max_length=100, null=True, verbose_name='Заголовок')),
                ('blog_annotation', models.CharField(blank=True, help_text='До 150 символов', max_length=150, null=True, verbose_name='Аннотация')),
                ('title', models.CharField(blank=True, help_text='До 70 символов', max_length=70, null=True, verbose_name='Метатэг Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
                ('meta_description', models.CharField(blank=True, help_text='До 300 символов', max_length=300, null=True, verbose_name='Метатэг Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='До 150 символов', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
                'permissions': [('content_management', 'Создавать статьи блога')],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_h1', models.CharField(blank=True, help_text='До 100 символов', max_length=100, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, help_text='До 70 символов', max_length=70, null=True, verbose_name='Метатэг Title')),
                ('official_company_name', models.CharField(blank=True, help_text='До 30 символов', max_length=30, null=True, verbose_name='Юридическое название')),
                ('country', models.CharField(blank=True, help_text='До 20 символов', max_length=20, null=True, verbose_name='Страна')),
                ('itin', models.CharField(blank=True, help_text='До 20 символов', max_length=20, null=True, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, help_text='До 50 символов', max_length=50, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='До 30 символов', max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, help_text='До 40 символов', max_length=40, null=True, verbose_name='Email')),
                ('meta_description', models.CharField(blank=True, help_text='До 300 символов', max_length=300, null=True, verbose_name='Метатэг Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='До 150 символов', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_h1', models.CharField(help_text='До 100 символов', max_length=100, verbose_name='Заголовок')),
                ('home_annotation', models.CharField(help_text='До 150 символов', max_length=150, verbose_name='Аннотация')),
                ('title', models.CharField(help_text='До 70 символов', max_length=70, verbose_name='Метатэг Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
                ('test_email', models.EmailField(blank=True, help_text='ПОЛЕ НЕ ДОЛЖНО БЫТЬ ПУСТЫМ', max_length=254, null=True, verbose_name='Почта для теста')),
                ('annotation_advantages', models.CharField(blank=True, help_text='До 100 символов', max_length=100, null=True, verbose_name='Заголовок перед блоком преимуществ')),
                ('annotation_posts', models.CharField(blank=True, help_text='До 100 символов', max_length=100, null=True, verbose_name='Заголовок перед блоком случайных постов')),
                ('picture', models.ImageField(blank=True, help_text='рекомендуемый размер - 2000*1000', null=True, upload_to='home/', verbose_name='Картинка в шапке')),
                ('count_all_mailings', models.IntegerField(blank=True, help_text='Если поле пустое - берется автоматически из БД', null=True, verbose_name='Всего рассылок')),
                ('step_all_mailings', models.IntegerField(default=1, help_text='Для корректировки скорости вывода разных по величине цифр', verbose_name='Шаг количества рассылок')),
                ('count_active_mailings', models.IntegerField(blank=True, help_text='Если поле пустое - берется автоматически из БД', null=True, verbose_name='Активных рассылок')),
                ('step_active_mailings', models.IntegerField(default=1, help_text='Для корректировки скорости вывода разных по величине цифр', verbose_name='Шаг активных рассылок')),
                ('count_users', models.IntegerField(blank=True, help_text='Если поле пустое - берется автоматически из БД', null=True, verbose_name='Количество пользователей')),
                ('step_users', models.IntegerField(default=1, help_text='Для корректировки скорости вывода разных по величине цифр', verbose_name='Шаг количества пользователей')),
                ('meta_description', models.CharField(blank=True, help_text='До 300 символов', max_length=300, null=True, verbose_name='Метатэг description')),
                ('meta_keywords', models.CharField(blank=True, help_text='До 150 символов', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='До 100 символов', max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
                ('picture', models.ImageField(blank=True, help_text='рекомендуемый размер - 2000*1000', null=True, upload_to='posts/', verbose_name='Фото')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('change_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('status', models.CharField(choices=[('опубликовано', 'ДА'), ('не опубликовано', 'НЕТ')], default='опубликовано', max_length=20, verbose_name='Публиковать?')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
        migrations.AlterModelOptions(
            name='configmailing',
            options={'permissions': [('view_and_ban_any_mailing', 'блокировать любую рассылку')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_and_ban_any_user', 'блокировать любого пользователя')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='configmailing',
            name='password_user_from_email',
        ),
        migrations.AddField(
            model_name='configmailing',
            name='banned',
            field=models.CharField(choices=[('ЗАБЛОКИРОВАНО МОДЕРАТОРОМ', 'ЗАБАНИТЬ'), ('одобрено модератором', 'РАЗБАНИТЬ')], default='одобрено модератором', max_length=30, verbose_name='Забанить пост?'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='password_from_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пароль от почты рассылки'),
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.CharField(choices=[('Заблокирован модератором', 'ЗАБЛОКИРОВАТЬ'), ('Не заблокирован', 'РАЗБЛОКИРОВАТЬ')], default='Не заблокирован', max_length=30, verbose_name='Забанить пользователя?'),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий пользователю'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email рассылки'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='periodicity',
            field=models.CharField(choices=[('Каждый день', 'Каждый день'), ('Один или несколько дней в неделю', 'Один или несколько дней в неделю'), ('Один или несколько дней в месяц', 'Один или несколько дней в месяц')], default='Каждый день', max_length=40, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Ожидает модерации', 'Ожидает модерации')], default='Создана', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='configmailing',
            name='title',
            field=models.CharField(help_text='максимальное количество символов - 100', max_length=100, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='lettermailing',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lettermailing',
            name='status',
            field=models.CharField(choices=[('Отправлено', 'Отправлено'), ('В ожидании', 'Ожидает отправки')], default='В ожидании', max_length=20, verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='lettermailing',
            name='title',
            field=models.CharField(help_text='максимальное количество символов - 50', max_length=50, verbose_name='Тема письма'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(default='Гость', max_length=50, verbose_name='Если хотите, укажите Ваще имя или псевдоним')),
                ('content', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.post')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
